CREATE DATABASE IF NOT EXISTS test_db
	DEFAULT CHARACTER SET = utf8
	DEFAULT COLLATE = utf8_general_ci;

USE test_db;

CREATE TABLE IF NOT EXISTS table_01 (
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	title VARCHAR(32) NOT NULL DEFAULT 'testing' 
);

CREATE TABLE IF NOT EXISTS table_02 (
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	title VARCHAR(32) NOT NULL DEFAULT 'testing' 
);

CREATE TABLE IF NOT EXISTS table_03 (
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	title VARCHAR(32) NOT NULL DEFAULT 'testing' 
);

